version: '3.7'
services:
  backend:
    build: ./backend
    command: npm run dev
    container_name: "backend"
    depends_on:
      - db
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/srv/backend
    restart: on-failure
    links:
      - db
  db:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: on-failure
